---
- name: Les clauses conditionnelles
  hosts: all

  tasks:
    - name: Bloc when
      block:
        - name: Clause when
          ansible.builtin.debug:
            msg: "Glop glop !"

        - name: Autre tâche et même when
          ansible.builtin.debug:
            msg: "Glop glop !"
      when:
        - ansible_distribution | lower == 'debian'
        - ansible_architecture == "x86_64" or ansible_distribution_version > 10

    - name: Tâche non idempotente
      ansible.builtin.raw: date
      changed_when: false

    - name: Tâche en échec (à ne pas gérer comme tel)
      ansible.builtin.raw: grep curt /etc/passwd
      register: result
      failed_when: result.rc > 1

    - name: Affichage variable result
      ansible.builtin.debug:
        msg: "Result: {{ result }}"

    - name: Bloc rescue
      block:
        - name: Tâche I
          ansible.builtin.debug:
            msg: "Tâche I"

        - name: Tâche II
          ansible.builtin.debug:
            msg: "Tâche II"
          failed_when: true

        - name: Tâche III
          ansible.builtin.debug:
            msg: "Tâche III"
      rescue:
        - name: Tâche de secours
          ansible.builtin.debug:
            msg: "SOS"
      always:
        - name: Tâche obligatoire
          ansible.builtin.debug:
            msg: "On passe toujours par ici"

    - name: Tâche finale
      ansible.builtin.debug:
        msg: "Fini !"
