---
- name: Installation logicielle
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Installation du serveur nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Configuration du service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
