---
- name: Micro-TP n°7
  hosts: all
  gather_facts: false

  tasks:
    - name: Chargement du fichier logins.yml
      ansible.builtin.include_vars:
        file: logins.yml

    - name: Affichage des groupes seulement
      ansible.builtin.debug:
        msg: "{{ item.1 }}"
      loop: "{{ logins | subelements('groups') }}"
