---
- name: Ansible et les variables
  hosts: all
  gather_facts: true

  vars:
    stage: Ansible

  tasks:
    - name: Chargement du fichier vars/stagiaires.yml
      ansible.builtin.include_vars:
        file: stagiaires.yml

    - name: Affichage et module debug
      ansible.builtin.debug:
        msg: "Formation: {{ stage }}"

    - name: Présentation de la notion de filtre
      ansible.builtin.debug:
        msg: "Durée {{ nb_jours | default(3) }} jours"
