---
- name: Micro-TP n°3 - Mise en œuvre de redis
  hosts: fedora-cli
  gather_facts: false
  become: true

  tasks:
    - name: Installation de redis
      ansible.builtin.package:
        name: redis
        state: present

    - name: Configuration du service
      ansible.builtin.systemd:
        name: redis
        enabled: true
        state: started

    - name: Configuration réseau de redis
      ansible.builtin.lineinfile:
        dest: /etc/redis/redis.conf
        regex: ^bind
        line: bind 192.168.56.246
        backup: true
      notify:
        - restart_redis

    - name: Tâche bidon
      ansible.builtin.debug:
        msg: "Dernière tâche"

  handlers:
    - name: Configuration du service
      ansible.builtin.systemd:
        name: redis
        state: restarted
      listen:
        - restart_redis
