---
- name: Les clauses conditionnelles
  hosts: all

  tasks:
    - name: Bloc when
      block:
        - name: Clause when
          ansible.builtin.debug:
            msg: "Glop glop !"

        - name: Autre tâche et même when
          ansible.builtin.debug:
            msg: "Glop glop !"
      when:
        - ansible_distribution | lower == 'debian'
        - ansible_architecture == "x86_64" or ansible_distribution_version > 10

    - name: Tâche non idempotente
      ansible.builtin.raw: date
      changed_when: false
