---
- name: Micro-TP n°7
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Chargement du fichier logins.yml
      ansible.builtin.include_vars:
        file: logins.yml

    - name: Création des groupes
      ansible.builtin.group:
        name: "{{ item.1 }}"
      loop: "{{ logins | subelements('groups') }}"

    - name: Création des utilisateurs
      ansible.builtin.user:
        name: "{{ item.login }}"
        home: "{{ item.home }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
      loop: "{{ logins }}"
